language: r
cache: packages

matrix:
  include:
    - os: linux
      r: release
    - os: osx
      r: release
  allow_failures:
    - os: osx
  fast_finish: true

branches:
  only:
    - master

env:
  global:
    - LINTR_COMMENT_BOT=true

r_packages:
  - covr
github_packages:
  - acidgenomics/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
