# R for travis
# https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: true

# Temporarily enable to cache R packages
# script: true

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
